/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas.Camarasweb;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class PantallaRegistro extends javax.swing.JFrame {
    int xMouse,yMouse;

     FondoPanel fondoR = new FondoPanel();
    public PantallaRegistro() {
       this.setContentPane (fondoR);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        TransparentePanel = new javax.swing.JPanel();
        barraPantalla = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        Panelinicio = new javax.swing.JPanel();
        lblRegistrarse = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        btnXiniciarSesion = new javax.swing.JButton();
        AunNoteunes = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        lblContraseña = new javax.swing.JLabel();
        lblCorreoOid = new javax.swing.JLabel();
        lblCorreoOid1 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblContraseña1 = new javax.swing.JLabel();
        lblContraseña2 = new javax.swing.JLabel();
        checkbox2 = new java.awt.Checkbox();
        txtCorreo = new javax.swing.JTextField();
        txtNombresUs = new javax.swing.JTextField();
        TextoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        TransparentePanel.setBackground(new java.awt.Color(0, 0, 0, 150));

        barraPantalla.setBackground(new java.awt.Color(0, 0, 0, 50));
        barraPantalla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraPantallaMouseDragged(evt);
            }
        });
        barraPantalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraPantallaMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(40, 40));

        btnExit.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setPreferredSize(new java.awt.Dimension(40, 40));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout barraPantallaLayout = new javax.swing.GroupLayout(barraPantalla);
        barraPantalla.setLayout(barraPantallaLayout);
        barraPantallaLayout.setHorizontalGroup(
            barraPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraPantallaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        barraPantallaLayout.setVerticalGroup(
            barraPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panelinicio.setBackground(new java.awt.Color(0, 0, 0));
        Panelinicio.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Panelinicio.setForeground(new java.awt.Color(255, 255, 255));

        lblRegistrarse.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        lblRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrarse.setText("REGISTRARSE");

        txtApellidos.setBackground(new java.awt.Color(28, 28, 28));
        txtApellidos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(255, 255, 255));
        txtApellidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidosMousePressed(evt);
            }
        });
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        btnXiniciarSesion.setBackground(new java.awt.Color(0, 0, 0));
        btnXiniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnXiniciarSesion.setText("REGISTRARSE");
        btnXiniciarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnXiniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXiniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXiniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXiniciarSesionMouseExited(evt);
            }
        });

        AunNoteunes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        AunNoteunes.setForeground(new java.awt.Color(255, 255, 255));
        AunNoteunes.setText("¿Ya tienes una cuenta?");

        btnRegistrarse.setBackground(new java.awt.Color(28, 28, 28));
        btnRegistrarse.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(0, 98, 221));
        btnRegistrarse.setText("INICIAR SESION");
        btnRegistrarse.setBorder(null);

        txtContraseña.setBackground(new java.awt.Color(28, 28, 28));
        txtContraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraseñaMousePressed(evt);
            }
        });

        lblContraseña.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("CONTRASEÑA");

        lblCorreoOid.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblCorreoOid.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreoOid.setText("NOMBRES");

        lblCorreoOid1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblCorreoOid1.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreoOid1.setText("APELLIDOS");

        txtNombres.setBackground(new java.awt.Color(28, 28, 28));
        txtNombres.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(255, 255, 255));
        txtNombres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombresMousePressed(evt);
            }
        });
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });

        lblContraseña1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblContraseña1.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña1.setText("NOMBRE DE USUARIO");

        lblContraseña2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblContraseña2.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña2.setText("CORREO");

        checkbox2.setBackground(new java.awt.Color(28, 28, 28));
        checkbox2.setForeground(new java.awt.Color(255, 255, 255));
        checkbox2.setLabel("Aceptas la politica de privacidad");

        txtCorreo.setBackground(new java.awt.Color(28, 28, 28));
        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        txtNombresUs.setBackground(new java.awt.Color(28, 28, 28));
        txtNombresUs.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombresUs.setForeground(new java.awt.Color(255, 255, 255));
        txtNombresUs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtNombresUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombresUsMousePressed(evt);
            }
        });
        txtNombresUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresUsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelinicioLayout = new javax.swing.GroupLayout(Panelinicio);
        Panelinicio.setLayout(PanelinicioLayout);
        PanelinicioLayout.setHorizontalGroup(
            PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelinicioLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelinicioLayout.createSequentialGroup()
                        .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraseña1)
                            .addGroup(PanelinicioLayout.createSequentialGroup()
                                .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCorreoOid))
                                .addGap(18, 18, 18)
                                .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCorreoOid1)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblContraseña2))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelinicioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AunNoteunes)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrarse)
                        .addGap(89, 89, 89))
                    .addGroup(PanelinicioLayout.createSequentialGroup()
                        .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombresUs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelinicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelinicioLayout.createSequentialGroup()
                        .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelinicioLayout.createSequentialGroup()
                        .addComponent(btnXiniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelinicioLayout.createSequentialGroup()
                        .addComponent(lblRegistrarse)
                        .addGap(135, 135, 135))))
        );
        PanelinicioLayout.setVerticalGroup(
            PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelinicioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCorreoOid)
                    .addGroup(PanelinicioLayout.createSequentialGroup()
                        .addComponent(lblRegistrarse)
                        .addGap(18, 18, 18)
                        .addComponent(lblCorreoOid1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContraseña1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombresUs, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContraseña2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXiniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AunNoteunes)
                    .addComponent(btnRegistrarse))
                .addGap(39, 39, 39))
        );

        TextoPanel.setBackground(new java.awt.Color(0, 0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 65)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html><center>¿ P A R A  Q U E<P>R E G I S T R A R S E?");
        jLabel3.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><center>Registrarse en un sistema de alarma antirrobos<p>proporciona una capa adicional de seguridad y<p>proteccion para tu hogar o negocio. Aunque implica un<p>costo inicial y posiblemente una tarifa de monitoreo<p>continua, muchos consideran que los beneficios en<p>terminos de seguridad y tranquilidad justifican esta<p>inversion.<html>");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout TextoPanelLayout = new javax.swing.GroupLayout(TextoPanel);
        TextoPanel.setLayout(TextoPanelLayout);
        TextoPanelLayout.setHorizontalGroup(
            TextoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(TextoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        TextoPanelLayout.setVerticalGroup(
            TextoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextoPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TransparentePanelLayout = new javax.swing.GroupLayout(TransparentePanel);
        TransparentePanel.setLayout(TransparentePanelLayout);
        TransparentePanelLayout.setHorizontalGroup(
            TransparentePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraPantalla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransparentePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(TextoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panelinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        TransparentePanelLayout.setVerticalGroup(
            TransparentePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransparentePanelLayout.createSequentialGroup()
                .addComponent(barraPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(TransparentePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransparentePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TextoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransparentePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Panelinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TransparentePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TransparentePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void barraPantallaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraPantallaMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);

    }//GEN-LAST:event_barraPantallaMouseDragged

    private void barraPantallaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraPantallaMousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();

    }//GEN-LAST:event_barraPantallaMousePressed

    private void txtApellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidosMousePressed
        if (txtApellidos.getText().equals("  Ingrese su apellido"))
        {
            txtApellidos.setText("");
            txtApellidos.setForeground(Color.white);
        }
        if (String.valueOf(txtContraseña.getPassword()).isEmpty())
        {
            txtContraseña.setText("  Ingrese su contraseña");
            txtContraseña.setForeground(Color.gray);
        }
        if (txtNombres.getText().isEmpty())
        {
            txtNombres.setText("  Ingrese su Nombre");
            txtNombres.setForeground(Color.gray);
        }
          if (txtNombresUs.getText().isEmpty())
        {
            txtNombresUs.setText("  Ingrese su Nombre de Usuario");
            txtNombresUs.setForeground(Color.gray);
        }  
          if (txtCorreo.getText().isEmpty())
        {
            txtCorreo.setText("  Ingrese su Correo");
            txtCorreo.setForeground(Color.gray);
        }  
    }//GEN-LAST:event_txtApellidosMousePressed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void btnXiniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXiniciarSesionMouseClicked

        javax.swing.JOptionPane.showMessageDialog(this,"Intento de login con los datos:\nUsuarios: " + txtApellidos.getText()+ "\nContraseña: " + String.valueOf(txtContraseña.getPassword()),"LOGIN" , javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnXiniciarSesionMouseClicked

    private void btnXiniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXiniciarSesionMouseEntered

        btnXiniciarSesion.setBackground(Color.blue);
    }//GEN-LAST:event_btnXiniciarSesionMouseEntered

    private void btnXiniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXiniciarSesionMouseExited

        btnXiniciarSesion.setBackground(Color.black);
    }//GEN-LAST:event_btnXiniciarSesionMouseExited

    private void txtContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMousePressed
        if (String.valueOf(txtContraseña.getPassword()).equals("  Ingrese su contraseña"))
        {
            txtContraseña.setText("");
            txtContraseña.setForeground(Color.white);
        }
        if (txtApellidos.getText().isEmpty())
        {
            txtApellidos.setText("  Ingrese su apellido");
            txtApellidos.setForeground(Color.gray);
        }
          if (txtNombres.getText().isEmpty())
        {
            txtNombres.setText("  Ingrese su Nombre");
            txtNombres.setForeground(Color.gray);
        }
          if (txtNombresUs.getText().isEmpty())
        {
            txtNombresUs.setText("  Ingrese su Nombre de Usuario");
            txtNombresUs.setForeground(Color.gray);
        }  
          if (txtCorreo.getText().isEmpty())
        {
            txtCorreo.setText("  Ingrese su Correo");
            txtCorreo.setForeground(Color.gray);
        }  
    }//GEN-LAST:event_txtContraseñaMousePressed

    private void txtNombresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombresMousePressed
   if (txtNombres.getText().equals("  Ingrese su Nombre"))
        {
            txtNombres.setText("");
            txtNombres.setForeground(Color.white);
        }
        if (String.valueOf(txtContraseña.getPassword()).isEmpty())
        {
            txtContraseña.setText("  Ingrese su contraseña");
            txtContraseña.setForeground(Color.gray);
        }
        if (txtApellidos.getText().isEmpty())
        {
            txtApellidos.setText("  Ingrese su apellido");
            txtApellidos.setForeground(Color.gray);
        }
          if (txtNombresUs.getText().isEmpty())
        {
            txtNombresUs.setText("  Ingrese su Nombre de Usuario");
            txtNombresUs.setForeground(Color.gray);
        }  
          if (txtCorreo.getText().isEmpty())
        {
            txtCorreo.setText("  Ingrese su Correo");
            txtCorreo.setForeground(Color.gray);
        } 
    }//GEN-LAST:event_txtNombresMousePressed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked

             System.exit(0);        
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered

        btnExit.setForeground(Color.red);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited


        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseExited

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
      if (txtCorreo.getText().equals("  Ingrese su Correo"))
        {
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.white);
        }
        if (String.valueOf(txtContraseña.getPassword()).isEmpty())
        {
            txtContraseña.setText("  Ingrese su contraseña");
            txtContraseña.setForeground(Color.gray);
        }
        if (txtApellidos.getText().isEmpty())
        {
            txtApellidos.setText("  Ingrese su apellido");
            txtApellidos.setForeground(Color.gray);
        }
          if (txtNombres.getText().isEmpty())
        {
            txtNombres.setText("  Ingrese su Nombre");
            txtNombres.setForeground(Color.gray);
        }  
          if (txtNombresUs.getText().isEmpty())
        {
            txtNombresUs.setText("  Ingrese su Nombre de Usuario");
            txtNombresUs.setForeground(Color.gray);
        }         // 

    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtNombresUsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombresUsMousePressed
      if (txtNombresUs.getText().equals("  Ingrese su Nombre de Usuario"))
        {
            txtNombresUs.setText("");
            txtNombresUs.setForeground(Color.white);
        }
        if (String.valueOf(txtContraseña.getPassword()).isEmpty())
        {
            txtContraseña.setText("  Ingrese su contraseña");
            txtContraseña.setForeground(Color.gray);
        }
        if (txtApellidos.getText().isEmpty())
        {
            txtApellidos.setText("  Ingrese su apellido");
            txtApellidos.setForeground(Color.gray);
        }
          if (txtNombres.getText().isEmpty())
        {
            txtNombres.setText("  Ingrese su Nombre");
            txtNombres.setForeground(Color.gray);
        }  
          if (txtCorreo.getText().isEmpty())
        {
            txtCorreo.setText("  Ingrese su Correo");
            txtCorreo.setForeground(Color.gray);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresUsMousePressed

    private void txtNombresUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresUsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AunNoteunes;
    private javax.swing.JPanel Panelinicio;
    private javax.swing.JPanel TextoPanel;
    private javax.swing.JPanel TransparentePanel;
    private javax.swing.JPanel barraPantalla;
    private javax.swing.JLabel btnExit;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnXiniciarSesion;
    private java.awt.Checkbox checkbox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblContraseña1;
    private javax.swing.JLabel lblContraseña2;
    private javax.swing.JLabel lblCorreoOid;
    private javax.swing.JLabel lblCorreoOid1;
    private javax.swing.JLabel lblRegistrarse;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNombresUs;
    // End of variables declaration//GEN-END:variables
   class FondoPanel extends JPanel
    {
            
     private Image imagen;
     @Override
     public void paint(Graphics g)
     { 
           imagen = new ImageIcon(getClass().getResource("/Imagenes/PRegistro.jpg")).getImage();
           g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
           setOpaque(false);
           super.paint(g);
     }
             
    }
}
